apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-rancher
spec:
  selector:
    matchLabels:
      app: hello-rancher
  template:
    metadata:
      labels:
        app: hello-rancher
    spec:
      containers:
      - name: hello-rancher
        image: rancher/hello-world
        ports:
        - containerPort: 80
          name: http